# Generated by Django 3.1.3 on 2020-12-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copr_name', models.CharField(max_length=30)),
                ('registration_number', models.CharField(max_length=30)),
                ('corp_discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_rate', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('customer_type', models.CharField(choices=[('C', 'Corporate'), ('I', 'Individual')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=30)),
                ('rent_charge', models.FloatField()),
                ('extra_charge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=5)),
                ('model', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=4)),
                ('lpn', models.CharField(max_length=6)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental.location')),
                ('vehicle_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental.vehicle_class')),
            ],
        ),
        migrations.CreateModel(
            name='Rental_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_date', models.DateField()),
                ('s_odometer', models.FloatField()),
                ('e_odometer', models.FloatField()),
                ('d_odometer_limit', models.FloatField()),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental.customer')),
                ('d_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_loaction', to='car_rental.location')),
                ('p_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_loaction', to='car_rental.location')),
                ('vin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=30)),
                ('payment_number', models.CharField(max_length=16)),
                ('inovice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='rental_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental.rental_service'),
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='car_rental.customer')),
                ('dln', models.CharField(max_length=10)),
                ('ins_name', models.CharField(max_length=30)),
                ('ins_no', models.CharField(max_length=30)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental.coupon')),
            ],
            bases=('car_rental.customer',),
        ),
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='car_rental.customer')),
                ('employee_ID', models.CharField(max_length=30)),
                ('corporation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental.corporation')),
            ],
            bases=('car_rental.customer',),
        ),
    ]
